source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
workspace 'PhotoPark'

target 'PhotoPark' do
    xcodeproj 'PhotoPark.xcodeproj'
    link_with ['Dev']
    pod 'Classy', :inhibit_warnings => true
    pod 'CocoaLumberjack'
    pod 'Masonry'
    pod 'POSRx', :git => 'https://github.com/pavelosipov/POSRx.git', :branch => 'immutable_options'
    pod 'POSJSONParsing', :git => 'https://github.com/pavelosipov/POSJSONParsing.git'
    pod 'RDHCollectionViewGridLayout'
end

target 'PhotoParkTests' do
    xcodeproj 'PhotoPark.xcodeproj'
    link_with ['Tests']
    pod 'CocoaLumberjack'
    pod 'POSRx', :git => 'https://github.com/pavelosipov/POSRx.git', :branch => 'immutable_options'
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SDKROOT'] = "iphoneos"
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
